---
# Setup permissions ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
# Setup permissions ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-service-account

---
# Setup permissions ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: monitoring-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: monitoring-service-account
    namespace: grafana-agent

---
# grafana deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        volumeMounts:
        - name: dashboard-config
          mountPath: /etc/grafana/provisioning/dashboards/dashboard.yml
          subPath: 'dashboard.yml'
        - name: json-dashboard-config
          mountPath: /etc/grafana/provisioning/dashboards/json
        - name: datasource-config
          mountPath: /etc/grafana/provisioning/datasources/datasource.yml
          subPath: 'datasource.yml'
      volumes:
      - name: dashboard-config
        configMap:
          name: dashboard-config
      - name: json-dashboard-config
        configMap:
          name: json-dashboard-config
      - name: datasource-config
        configMap:
          name: datasource-config

---
# grafana service 3000
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000

---
# minio deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        command: ["sh", "-c", "mkdir -p /data/loki && mkdir -p /data/mimir && minio server --quiet /data --console-address \":9001\""]
        env:
        - name: MINIO_ROOT_USER
          value: myminio
        - name: MINIO_ROOT_PASSWORD
          value: mypassword

---
# minio service 9000 and 9001
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    name: "9000"
  - port: 9001
    targetPort: 9001
    name: "9001"

---
# mimir deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
      - name: mimir
        image: grafana/mimir:latest
        # hostame: mimir-1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: ["-config.file=/etc/mimir.yml"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mimir-config
          mountPath: /etc/mimir.yml
          subPath: 'mimir.yml'
        - name: alertmanager-config
          mountPath: /etc/alertmanager-fallback-config.yaml
          subPath: 'alertmanager.yml'
      volumes:
      - name: mimir-config
        configMap:
          name: mimir-config
      - name: alertmanager-config
        configMap:
          name: alertmanager-config

---
# mimir service 8080
apiVersion: v1
kind: Service
metadata:
  name: mimir-service
spec:
  type: NodePort
  selector:
    app: mimir
  ports:
  - port: 8080
    targetPort: 8080

---
# loki deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: ["--config.file=/etc/loki/config.yml"]
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki/config.yml
          subPath: 'loki.yml'
      volumes:
      - name: loki-config
        configMap:
          name: loki-config

---
# loki service 3100
apiVersion: v1
kind: Service
metadata:
  name: loki-service
spec:
  type: NodePort
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100

---
# grafana-agent DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-agent-deployment
spec:
  selector:
    matchLabels:
      app: grafana-agent
  template:
    metadata:
      labels:
        app: grafana-agent
    spec:
      serviceAccountName: monitoring-service-account
      containers:
      - name: grafana-agent
        image: grafana/agent:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["/usr/bin/bash", "-c", "/configs/entrypoint.sh george-kube-logs"]
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        volumeMounts:
        - name: entrypoint-config
          mountPath: /configs/entrypoint.sh
          subPath: 'entrypoint.sh'
        - name: prometheus-custom-config
          mountPath: /configs/prometheus-custom.yml
          subPath: 'prometheus-custom.yml'
        - name: prometheus-config
          mountPath: /configs/prometheus.yml
          subPath: 'prometheus.yml'
        - name: promtail-config
          mountPath: /configs/promtail.yml
          subPath: 'promtail.yml'
        - name: containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
      volumes:
      - name: entrypoint-config
        configMap:
          name: entrypoint-config
          defaultMode: 0775
      - name: prometheus-custom-config
        configMap:
          name: prometheus-custom-config
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: promtail-config
        configMap:
          name: promtail-config
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: pods
        hostPath:
          path: /var/log/pods

# ---
# # test-promtail DaemonSet
# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: test-promtail-deployment
# spec:
#   selector:
#     matchLabels:
#       app: test-promtail
#   template:
#     metadata:
#       labels:
#         app: test-promtail
#     spec:
#       serviceAccountName: monitoring-service-account
#       containers:
#       - name: test-promtail
#         image: grafana/promtail:latest
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "250m"
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         args: ["--config.file=/etc/promtail/promtail.yml"]
#         env:
#           - name: HOSTNAME
#             valueFrom:
#               fieldRef:
#                 apiVersion: v1
#                 fieldPath: spec.nodeName
#         volumeMounts:
#         - name: test-promtail-config
#           mountPath: /etc/promtail/promtail.yml
#           subPath: 'test-promtail.yml'
#         - name: containers
#           mountPath: /var/lib/docker/containers
#           readOnly: true
#         - name: pods
#           mountPath: /var/log/pods
#           readOnly: true
#       volumes:
#       - name: test-promtail-config
#         configMap:
#           name: test-promtail-config
#       - name: containers
#         hostPath:
#           path: /var/lib/docker/containers
#       - name: pods
#         hostPath:
#           path: /var/log/pods
