scrape_configs:
  - job_name: 'vouch'
    static_configs:
      - targets: ['vouch-metrics:8081']
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik-metrics:8080']

global:
  external_labels:
    cluster: lido5-vouch-george
    environment: lido5-george

  remote_write:
    - url: http://loki:3100/loki/api/v1/push
