auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: error

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /loki/wal
    enabled: true
    replay_memory_ceiling: 3GB

schema_config:
  configs:
  - from: 2022-02-20
    store: tsdb
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

storage_config:
 tsdb_shipper:
   active_index_directory: /loki/index
   cache_location: /loki/index_cache
   shared_store: s3

 aws:
  bucketnames: loki
  endpoint: minio-service:9000
  region: ''
  access_key_id: myminio
  secret_access_key: mypassword
  insecure: true
  sse_encryption: false
  http_config:
    idle_conn_timeout: 90s
    response_header_timeout: 0s
    insecure_skip_verify: false
  s3forcepathstyle: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /tmp/rules/fake/
#  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true